#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/neymar

###

POST http://localhost:3333/neymar
Content-Type: application/json

{
    "idade": "32",
    "posição": "Meia Atacante",
    "nome_da_esposa": "Bruna Biancardi"
}

###

PUT http://localhost:3333/neymar/id
Content-Type: application/json

{
    "idade": "32",
    "posição": "Meia Atacante",
    "nome_da_esposa": "Bruna Biancardi"
}

###

DELETE http://localhost:3333/users/id
